// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// SLORangeMsApplyConfiguration represents a declarative configuration of the SLORangeMs type for use
// with apply.
//
// SLORangeMs defines a millisecond range for an SLO metric.
// MinMs is inclusive, MaxMs is exclusive: [MinMs, MaxMs).
// Omitting MinMs implies 0 (no lower bound).
// Omitting MaxMs implies no upper bound.
type SLORangeMsApplyConfiguration struct {
	// MinMs is the inclusive lower bound of the SLO range in milliseconds.
	MinMs *int64 `json:"minMs,omitempty"`
	// MaxMs is the exclusive upper bound of the SLO range in milliseconds.
	MaxMs *int64 `json:"maxMs,omitempty"`
}

// SLORangeMsApplyConfiguration constructs a declarative configuration of the SLORangeMs type for use with
// apply.
func SLORangeMs() *SLORangeMsApplyConfiguration {
	return &SLORangeMsApplyConfiguration{}
}

// WithMinMs sets the MinMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinMs field is set to the value of the last call.
func (b *SLORangeMsApplyConfiguration) WithMinMs(value int64) *SLORangeMsApplyConfiguration {
	b.MinMs = &value
	return b
}

// WithMaxMs sets the MaxMs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxMs field is set to the value of the last call.
func (b *SLORangeMsApplyConfiguration) WithMaxMs(value int64) *SLORangeMsApplyConfiguration {
	b.MaxMs = &value
	return b
}
