// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha2

// SLOSpecApplyConfiguration represents a declarative configuration of the SLOSpec type for use
// with apply.
//
// SLOSpec defines the expected SLO ranges for this objective.
type SLOSpecApplyConfiguration struct {
	// TTFT defines the expected Time To First Token SLO range in milliseconds.
	// The range bounds correspond to values expected in the x-slo-ttft-ms request header.
	TTFT *SLORangeMsApplyConfiguration `json:"ttft,omitempty"`
	// TPOT defines the expected Time Per Output Token SLO range in milliseconds.
	// The range bounds correspond to values expected in the x-slo-tpot-ms request header.
	TPOT *SLORangeMsApplyConfiguration `json:"tpot,omitempty"`
}

// SLOSpecApplyConfiguration constructs a declarative configuration of the SLOSpec type for use with
// apply.
func SLOSpec() *SLOSpecApplyConfiguration {
	return &SLOSpecApplyConfiguration{}
}

// WithTTFT sets the TTFT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTFT field is set to the value of the last call.
func (b *SLOSpecApplyConfiguration) WithTTFT(value *SLORangeMsApplyConfiguration) *SLOSpecApplyConfiguration {
	b.TTFT = value
	return b
}

// WithTPOT sets the TPOT field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TPOT field is set to the value of the last call.
func (b *SLOSpecApplyConfiguration) WithTPOT(value *SLORangeMsApplyConfiguration) *SLOSpecApplyConfiguration {
	b.TPOT = value
	return b
}
